# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/90532/Desktop/Python/Projeler/Mander Model/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Mander-Model")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 700))
        MainWindow.setMaximumSize(QtCore.QSize(600, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 279, 67))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fc = QtWidgets.QLineEdit(self.layoutWidget)
        self.fc.setObjectName("fc")
        self.gridLayout_2.addWidget(self.fc, 0, 1, 1, 1)
        self.fs = QtWidgets.QLineEdit(self.layoutWidget)
        self.fs.setObjectName("fs")
        self.gridLayout_2.addWidget(self.fs, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 30, 281, 93))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.b = QtWidgets.QLineEdit(self.layoutWidget1)
        self.b.setObjectName("b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.b)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.d = QtWidgets.QLineEdit(self.layoutWidget1)
        self.d.setObjectName("d")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.d)
        self.paspayi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.paspayi.setObjectName("paspayi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paspayi)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 140, 456, 115))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 1)
        self.dnx = QtWidgets.QLineEdit(self.layoutWidget2)
        self.dnx.setObjectName("dnx")
        self.gridLayout.addWidget(self.dnx, 2, 2, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.s = QtWidgets.QLineEdit(self.layoutWidget2)
        self.s.setObjectName("s")
        self.gridLayout.addWidget(self.s, 4, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 4, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.dny = QtWidgets.QLineEdit(self.layoutWidget2)
        self.dny.setObjectName("dny")
        self.gridLayout.addWidget(self.dny, 3, 2, 1, 3)
        self.lnx = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lnx.setObjectName("lnx")
        self.gridLayout.addWidget(self.lnx, 2, 5, 1, 2)
        self.lny = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lny.setObjectName("lny")
        self.gridLayout.addWidget(self.lny, 3, 5, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 270, 581, 401))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.layoutWidget3)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(560, 0, 16, 21))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Mander-Model", "Mander-Model"))
        self.label_4.setText(_translate("MainWindow", "Malzeme Mander Modeli"))
        self.fc.setText(_translate("MainWindow", "30"))
        self.fs.setText(_translate("MainWindow", "420"))
        self.label.setText(_translate("MainWindow", "Beton Basınç Dayanımı (MPa)"))
        self.label_2.setText(_translate("MainWindow", "Çelik Akma Dayanımı (MPa)"))
        self.label_3.setText(_translate("MainWindow", "Beton Paspayı (cm)"))
        self.b.setText(_translate("MainWindow", "50"))
        self.label_7.setText(_translate("MainWindow", "Kesit Kısa Kenarı (cm)"))
        self.d.setText(_translate("MainWindow", "30"))
        self.paspayi.setText(_translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "Kesit Uzun Kenarı (cm)"))
        self.label_5.setText(_translate("MainWindow", "Kesit Ana Donatısı"))
        self.dnx.setText(_translate("MainWindow", "4"))
        self.label_14.setText(_translate("MainWindow", "Etriye Aralığı (cm)"))
        self.s.setText(_translate("MainWindow", "10"))
        self.pushButton.setText(_translate("MainWindow", "Modelle"))
        self.label_8.setText(_translate("MainWindow", "Kesit Etriye Donatısı"))
        self.dny.setText(_translate("MainWindow", "2"))
        self.lnx.setText(_translate("MainWindow", "5"))
        self.lny.setText(_translate("MainWindow", "3"))
        self.label_11.setText(_translate("MainWindow", "Adet"))
        self.label_13.setText(_translate("MainWindow", "Uzun Yön"))
        self.label_12.setText(_translate("MainWindow", "Adet"))
        self.label_10.setText(_translate("MainWindow", "Kısa Yön"))
        self.label_9.setText(_translate("MainWindow", "Çap (mm)"))

